### ISSUE TITLE
The API index by request? 

### ISSUE THREAD

**Issue by WolfDan** [irfan-dahir/jikan#25]
I'm collecting info from your API, the first round many animes give me error 500 or others, second run it works fine.

So if it crawl by request, maybe you need put this info on the README (any way, I think right now you have 13000+ animes thanks too all my request [sorry for the "little attack" I don't want parse again all mal, just to get the info anime and crawl data etc...])

PD: Also some request return false as response, what it means?

**Comment by irfan-dahir** [comment]
The 500 error pops up on the first run. This is perhaps due to the monitoring script for rate limiting or cache script. Not sure, but I'll be fixing this ASAP.

No worries about the amount of requests, I got a bit of info on the usability and performance of the API to improve it. :)

Could you tell me which request is giving you a "false" response? Error responses are usually with invalid endpoints or using POST instead of GET.

**Comment by WolfDan** [comment]
I'm running again my vps to get the data and give you exactly what animes gives false, any way I found something:

If I run more than vps at the same time getting different data, it will give more 500 error, if I run just 1 vps at time it works normally
