### ISSUE TITLE
Rename genre to genres on manga endpoint

### ISSUE THREAD

**Issue by BlackSynder** [irfan-dahir/jikan#35]
Anime uses genres, so I thought it would be nicer to have it uniform and name it genres in Manga as well. (already made my code fail once haha)

**Comment by irfan-dahir** [comment]
Oops, this is embarrassing. I've removed multiple suffixes of the use of 's' after some array type elements. Such as 'authors' -> 'author' and 'genres' -> 'genre' since the 0.2.3 alpha  (June 2, 17) source.

It seems I've forgotten to unify it for some 'endpoints'. I'll be releasing a patch for this today.

It'll be 'genre' from now. :)

**Comment by BlackSynder** [comment]
Ah I see. Thanks!

**Comment by irfan-dahir** [comment]
I've just released a patch for it.

Read this for the changes.
https://github.com/irfan-dahir/jikan#026-beta---june-21-17

**Comment by BlackSynder** [comment]
actually, @irfan-dahir it seems anime still uses 'genres'.

**Comment by irfan-dahir** [comment]
Ah, that's the cache. I've cleared it so it should be updated one now.
